# Generated by Django 5.2.3 on 2025-07-03 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin888',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lad', models.IntegerField(default=650)),
                ('name', models.CharField(max_length=25)),
                ('pw', models.CharField(max_length=10)),
                ('price_thb', models.FloatField(blank=True, default=0, null=True)),
                ('price_lak', models.FloatField(blank=True, default=0, null=True)),
                ('price_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default='royal558.com', max_length=25)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Bin888',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_datetime', models.DateTimeField()),
                ('total_sale_price_thb', models.FloatField(blank=True, default=0, null=True)),
                ('total_sale_price_lak', models.FloatField(blank=True, default=0, null=True)),
                ('total_sale_bonus', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sale Records',
            },
        ),
        migrations.CreateModel(
            name='BinDataChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('progress_details', models.JSONField(blank=True, null=True)),
                ('old_username', models.CharField(blank=True, max_length=255, null=True)),
                ('old_password', models.CharField(blank=True, max_length=255, null=True)),
                ('old_customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_username', models.CharField(blank=True, max_length=255, null=True)),
                ('new_password', models.CharField(blank=True, max_length=255, null=True)),
                ('new_customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('sale_price_thb', models.FloatField(blank=True, default=0, null=True)),
                ('sale_price_lak', models.FloatField(blank=True, default=0, null=True)),
                ('sale_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('bin888', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app888.bin888')),
                ('salerecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app888.salerecord')),
            ],
            options={
                'unique_together': {('salerecord', 'bin888')},
            },
        ),
        migrations.AddField(
            model_name='salerecord',
            name='items',
            field=models.ManyToManyField(through='app888.SaleRecordItem', to='app888.bin888'),
        ),
    ]
