"""
Django settings for suekhay project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b268k(-&tu#!+l&v3=%pk=ah@w@zqk_x4+e=(%s$%(!rr7b!q('
# SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-fallback-insecure-key-for-local-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*'] # เปลี่ยน 'yourusername' เป็น username จริงของคุณ
# ALLOWED_HOSTS = ['yourusername.pythonanywhere.com'] # เปลี่ยน 'yourusername' เป็น username จริงของคุณ


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    # "crispy_bootstrap4",
    "crispy_bootstrap5",
    'app888',
    'apptest',
]

# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

# CRISPY_TEMPLATE_PACK = "bootstrap4"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'suekhay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suekhay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# ... การตั้งค่าอื่นๆ ...

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # เพิ่มบรรทัดนี้

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# your_project_name/settings.py
# ...
LOGOUT_REDIRECT_URL = '/'  # กำหนดให้ Redirect ไปที่หน้าแรกหลังจาก Logout สำเร็จ
# ...
# หากคุณไม่มีค่าใน Environment Variable (เช่นตอน dev บนเครื่อง local) มันจะใช้ค่าที่สอง
# แต่ใน Production บน PythonAnywhere เราจะตั้งค่า DJANGO_SECRET_KEY ผ่านหน้าเว็บ
import sys

# กำหนด path ไปยัง root folder ของโปรเจกต์ Django ของคุณ
# project_home = '/bin888/suekhay' # เปลี่ยน 'yourusername'
# if project_home not in sys.path:
#     sys.path.insert(0, project_home)

# # กำหนด DJANGO_SETTINGS_MODULE ให้ชี้ไปยังไฟล์ settings ของคุณ
# os.environ['DJANGO_SETTINGS_MODULE'] = 'suekhay.settings' # เปลี่ยน 'suekhay' ถ้าชื่อโปรเจกต์หลักต่างไป

# from django.core.wsgi import get_wsgi_application
# application = get_wsgi_application()